<template>
  <div class="container about-container">
    <section class="section">
      <h1 class="title is-1">Artist Statements</h1>
      <p class="subtitle is-3">Generated by OpenAI's GPT-3</p>
      <div class="content">
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I am interested in the relationship between people and objects. The way we use things in our daily lives is sometimes more interesting than the objects themselves. How the use of a simple object, such as a teapot, can create a ritual in our lives is fascinating to me.
        </p>
        <p>
        My passion for handmade objects was sparked by a childhood surrounded by woodworkers. My father and grandfather were both skilled woodworkers and I watched and learned from them. I continued my education at the University of Kentucky where I graduated with a degree in sculpture.
        </p>
        <p>
        My interest in clay emerged at a ceramic workshop while visiting a friend in Seattle. I was drawn to the music of the wheel and the way the clay would tell me what it wanted to become. The feel of the work in my hands and the way the clay would respond to the slightest change in pressure was amazing to me. This was my first experience with clay and I was hooked.
        </p>
        <p>
        The clay I use is from Kentucky, the water I use is from Kentucky and I fire in a Kentucky kiln. Kentucky is where I live and where I make my work. I am interested in the unique connection between people and place and I am inspired by my surroundings.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My work is inspired by the natural world: the flora and fauna around me, as well as the intricacy of both natural geologic structures and the human body. 
        </p>
        <p>
        As with the natural world, imperfections are not considered flaws, but rather as the source of beauty. In nature, layers of paint will be worn away at the base of cliffs and rock structures exposing the natural formations underneath in their own contrapuntal form. It is the same with people; scars and wrinkles are the life and journey still present on the body of the elderly. It is this imperfection that the work strives to make manifest. 
        </p>
        <p>
        My work is both functional and sculptural. The object is part of everyday life but at the same time stands out, calling us to wonder at the forms we make and the forms of nature. Perfectly joined up one cannot tell where the object stopped and the skill of the maker began. Therefore the day-to-day utility of a jug, or bowl or jar is both only itself and also, in its perfect imperfections, a reminder of the natural world outside of the human realm.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Ceramics is a rigid medium in terms of bending coils and pouring glazes but the molten clay material is as fluid and capable as water ever was. While there is a rigidity to the clay, overall there is not a fixed frame of time this "fluidity" has to fit within, I can hold the "fluid" back and let it slowly begin to flow again. This is the experience of my work. I think of my work in terms of fluid dynamics, while it is contained in its form there is an ebb and flow to it. Over time as this relates to the history of ceramic materials, the composition, the stacking and assembling during their dance into and out of the kiln evolve. It is the sense that when the forms of clay came into my hands that I was only holding the tip of an iceberg. From these veins the pot emerges. The pot comes from these veins and from the ebb and flow of the structures clay is capable of. It is this ebb and flow which pushes back and forth that are the visual cues and choreographic movements. Each stack of bowls, pots and dishes emerges slowly as if suspended like a series of waves within the overall composition. In this way there is a quality of five movement meshed into the whole. Over time as this ceramic sea or ocean ebbs and flows into its final space it has a quality of becoming its own landscape. The forms emit a sound, spoken into existence from someone sitting in silence. A series of short skits all fusing together for the life time performance. Over time each ceramic piece has a sense of turning into its most natural self and where imagined to be present and visible so it may live, a hug for the imagination and a portal into the world of the imagination and visual fantasy
        </p>
        <p>
        The forms are additive to one another and at the same time take away from one another. The forms are layered one over the other, and sometimes curl into each other. There is an oscillating effect in that not only stacking but over time in their travels back and forth the forms coming out
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Playing with the world of technology and 3D animation, I have created something new. From traditional hand painting techniques to digital environments that surround the human form.
        Through technological experimentation I recreated the world; let me tell my story of the ambiguous place between reality and illusion.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My sensual work is based on the nuance and textures found in nature and everyday life. The work is characterized by a limited color palette and precision between each color note. My keen awareness of the tactile rhythms of colour and form is never forced or arranged to suit an outside subjective opinion. The desire to arrange visual sensations is found within. The finished pots are concentrated fruit of my time speaking with you. The work both reveals its indebtedness to the past and celebrates the discovery of new ways to use everyday things.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My work is an exploration of ideas and values held within the basic building blocks of mass production—manufacturing, packaging and distribution. The works are assemblages that celebrate conflict and create objects that appear as either functional or decorative. Although they are an accumulation of ready to go items, these pieces are about the missing elements. I feel there is a vacuum to be filled or a space/story to be told; the action of it is the search.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The maquettes that have a foundation in architecture and monuments work as a metaphor for society particularly as we approach the state of the union of things, buildings, monuments and ideas. They all make up some great idea of what we could or should be.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Leery of mechanical perfection in art, I invoke improvisation as an aesthetic. Mired by doubts, shackled by fears, I have a need for the improbable. My love for all things imperfect led me to pottery, where slips, streaks, dents, and mends contribute to the final, thin-walled, highly-glazed objects exploring complex process and confusion. Soup cans embody our reluctance to accept ambiguity. Improvising a pot is a logical progression, a way to acknowledge chaos. In a world so ordered, where everything is catagorized, sorted and described… my upbringing in Miami, Florida enforced this “sweet see-saw” kind of thinking. Fontainebleau sand, highway blacktop, dirt, dried palm leaves, sun and surf became constants. Witnessing the longsuffering, dazzling front of the Florida keys under a constant bombardment of 8-12′ Northerly swell seemed to tacitly accept the reality of change, and therefore consistent abrasion. I think it is this acceptance, mixed with an equal amount of influence absorbed while living the next 12 years in Portugal, playing soccer in the Alentejo region and encountering the Old-new architecture of that part of country that ultimately enticed me to attempt the “Self-fulfilling prophecy” of pottery in order to resolve issues of a brittle, exposed nerve. Its a great relief, to be able to stop fighting the process, to be able to enjoy those bits of broken slip on the rim of the foot, the perfection of a tiny but necessary slip bubble, the pleasure gained from bringing the object to the brink of failure. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        This work exhumes objects that should be relegated to memory, those objects from our past that once seemed so bright and new. Usually when the time arrives to buy new ones, one realizes that they cannot be replaced. This abrupt transition series from the past to the present attempts to suspend us in the transformation. The once shiny and flashy becomes dull and tarnished and then gradually loses its relevance, its meaning. There is a direct correlation between the lifespan of a fossil and the perception that we have of them.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Clay is my palette. Clay becomes my paint brush and knife. I work the clay filling the voids and forming the geometric. I press the clay to distort it, unite it, and play with it. As the clay becomes a finished work, it retains the physical memory of my interaction with it. As I’ve said time and time again, clay is my voice.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Artists must take risks. We must work in the fear of failure. We must dare to make an impression on the world. Artists are the prism through which light is refracted. No color, no spectrum, no rainbow of options; just the purest form of white light contains all other colors, if you break the prism. Those creative risks are always overlooked with hindsight. The result is never as successful as we hope. The color never as brilliant as we projected. What has resulted is instead, something different. Something unexpected. Something better.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Trying to fix something that isn't broken just results in “fixed”. 
        Instead, I ask, how can we evolve this? How can we tell holistic stories? What if we flipped the subject or then simply turned it on it’s side? What if we looked at one meaningful collection from many points of view?
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Make a mark in the average. Try a different perspective. Move a few steps back. Take a moment to stop and look around. Now that you're talking to me, how can we change the subject?
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I am especially interested in how objects in nature can be mimicked in ceramic and how matter can seemingly be transformed to disappear under a glaze. To drag the surface of a clay body flat as glass, to capture the essence of a living root, or capture a shard of beach glass on its journey to becoming sand; these are my objects of desire. This line of investigation evolves from my masters in sculpture, my realization of the flatness of paper and paint as symbols to ideas and ideals, and my desire to use ceramics with spontaneity and experience rather than precision and control. I play with volumes, manipulating and inverting shapes, inviting light to shine on surprise inside.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Research drives my work to achieve new triumphs and new failures. The language of tradition, the story of the form, and the structure of junk food commercials link my interests to the form of collections and consider that while things are in flux, seemingly fixed, they are actually moving forward toward their end. I am inspired by many recent publications about anthropology and sociology and how objects are alive like ideas, like skin, like bones and waves.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The acts of manufacturing and of buying ceramics entail unique types of problems that are restorative. They seem more closely related than I first imagined. The right type of problem can push the imagination, or be the beginning or end of the creation of an object, or merely provide a field in which one desire can meet another, allowing the parts of an image to flourish. Thus objects manage to represent themselves, for they reveal their simultaneous functions and desires. In this way, a sink can become a vessel. A drain can become regular dishware or the circle of a wheel. It is an artist’s job to recognize opportunities, potential complications, and to lead these an audience to them.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        In a time of globalization, most of my work is provocatively idiosyncratic and personal. I apply surface to form thinking the details of the moment are most valuable. Striving for virtuosity in the everyday tasks such as color application, surface handling and form making serve as an enjoyable meditation for me. The essence of my handmade decorated pots begins with ideation on how to best extract the expression from the canvas I choose – the maturing thoughts manifest into the clay… as the making says.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I play with contrasts! I make use of transparency and translucency, but also of darkness and of light; of smoothness and of roughness. I make contradiction. Sometimes with sharp edges, other times with perfectly flat semispheres, bubble shapes, triangles or squares. Beauty also resides in power. Power, which evokes astonishment and is inherent in precision. This goes for rough as well as smooth. Sharp. Riding on this wave, however, is not always easy. The important task here is to gather sufficient strength and to simultaneously be reserved with regard to the sudden attacking image. To never lose the energy and dynamism but at the same time remain calm, pondering, composed and stick to the very important process. It only converts in quick moves and is completed with control.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The strength of our craft lies in its traditional elements and techniques. Its base is the skillful, methodical manipulation of clay to create forms and functional uses that are functional, uncomplicated and aesthetically satisfying without being derivative. We must celebrate the subtlety in the complement of shapes and textures in our most basic forms which allow our works to integrate into the ambiences with which they are surrounded both in their permanent and temporary functions.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Over the past fifteen years I have taken my exploration into expression through clay to the next level. Work has always been present as a means to connect with the greater consciousness as I understand it in this dimension. Drawing inspiration from symbolic things found in nature and daily life, I create functional stoneware that serves as personal declaration. Many parallels are found between artisans hand building vessels of clay and images being formed from thought. Their conception, manipulation and materialization are tools to decipher and ultimately make leaps into understanding the essential mystery of being.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        There is no question that I am a potter when working with clay. There is a magnifyed sense of presence as potter, as creator. The clay acts as a facilitator for my creative intuitions. The clay can not tell you what to do. You have to trust your inspirations and put them together, try to balance them against what you know. Clay can only be the gift of form and presence; the creator has to respond to that presence.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The genre of sculptural vessels made of earthenware must walk a fine line between content and form or risk inconsistent repression of either. The creation must serve as a vibrant link between both from creation to finished creation. Whether it holds or serves my engagement with poetry, it is ultimately the responsibility of the works to speak for the poet and painter as their player. Using earthenware as a sculptural clay allows the ability to play with a wide range of form, slip application, expressiveness, structural placement and lighting. Consequently, I choose Brown Mountain slip and porcelain surface for their unmatched ability and beauty for sculptural forms. It is this use of color, light and form which allows the juxtaposition to the expression its power. Poetry is less about the words than the place where the words find you, where the words become you, and the poem and verse is simultaneously a birth of place, person, and place once again.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Stoneware signifies chaos and destruction in its ancient mythic context. I play with the conflicted ideas of ultimate annihilation or rebirth at the hands of a divine hand. Transformation from the terrifying to the tranquil can be found in my approach to multi-faceted form. The forms are created in multiple parts from shaped slabs and thrown underglazes and glazes in my LA kiln studio. Overglaze painting and slurry application in my wood-fired LA studio completes the method of reassembly. The kiln fired transforms are utilized in Pasadena at the Ravenstrom Gallery for their wood-fire and raku exhibitions.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Through my upcoming pottery, I sit with the familiar and see with new eyes; by filling pots and bowls with wisdom, I explore the commonalities of women with similar expressions of the body and choices in clothing. Upon considering common ground, I hone into the disparities; embodied and attired in clay from similar yet contrasting earth, my pots sit in dialogue with each other and expose intrinsic common ground; emotions, behaviours, ideas and physical conditions. Textural and temperature gradients are created from low to high temp firings. Withstanding all outside influence, my pots segue from representing harmony, to losing their sense of self, call to chaos, and then seeking transformation. Embracing the wild, and the use of my hands, I mold forms that bleed, spill, grow, and burst; it is all the same, all part of change. Highlighting the pot's inherent tactility and colouration, four seemingly different clay bodies, converse one to another through gradient movement of heaviness and color. From hand to hand, from one body to another, I invite my pots to connect, to move and breathe one into another. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        In every fibre of our being we are aware of the detailed and fragile relationship between our physical world and that which surrounds us. I spin surfaces to capture an atmosphere of ascension, embodiment and shard matter. How fragile the frayed edges are of our experiences and memories, easily torn by the strains of our existences. At the heart of all is the acknowledgement of our inevitable terminations of birth, death, both hemispheres, and beyond all scientific explanation remain the boundaries of what we ourselves cannot define. The question of “what came before” and “what comes after”, “what is that is actually us” is subjective and somehow achieved. It is a journey between discovering where we come from, what is our legacy and whether or not we have owned it.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Working in ceramics has a limited range of feeling and texture to convey the soul inside an object. My work is about thoughtful placement, distinctive materialality and how the vessel chooses it’s home. The pieces explore in a way that takes the viewer from an expected comfort into an extraordinary intimacy, well beyond the pleasantries that we normally associate with our consumption. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I observe the landscape and scan the skies for sturdy nourishment – for health, to root its self safely in the earth, and for life-breath – that which fills with a declaration of its own objectives. The roots observe rightly the primal law of adaptation, constantly hiding, adapting, both always seeking safety and liberty. This is where my practice and my understanding of family history collide, for searching my family line accounts the resilience of the plants that survived and thrived off a land unforgiving enough to destroy them. My work explores the boundary of creation, rebirth, and evolution. It invites the viewer into an adaptation of their own as they enter into the opened conversations of dirt, matter, silt and objects to find hope.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Working in clay comes naturally to me – the fluid warmth of it feels, sounds and vibrates pervasively. I slowly draw out the character of the clay through the use of long and repetitive hand methods. I believe that clay has a mind of its own and by using the pot as an instrument, I ask it to expose the inner soul.
        Infatuated by the holy simplicity of a curve, I work the clay to find my places; old and remembered shapes, draped in nostalgia live a second life and are reincarnated from floating shards into sculptural vessels.
        </p>
        <p>
        In celebration of the fluid movement of a life in the deep south of Australia – cultural traditions – its art, stories, hopes, and dreams; I am exploring the reach of our creative spirit. I’ve set the stage for a conversation between the natural and cultural activity that has been entrenched here since the beginning of time. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My pots are the third of my bodies of work, inspired close to one and other, unified with an underlying thread disappearing and appearing again. With this in mind, I have drawn upon the archetypal idea of the vessel as an extension of and metaphor to, the body. Borne from three different cultural movements: the process-heavy Northern European ceramic tradition; naive folk pottery aesthetics from the South of France; and contemporary hand-building techniques developed in California, the ceramic pieces of the playfully named collection VESSEL RESONANCE, are wrapped in a delicate tension between form and space. Pot liquor and slip moves across half-dried surfaces; gravity creates patina-like effects; markings from pots used to support others poke through to the surface. The objects push and pull against each other, creating a physical tension rising from surface details. The play of various textures, surfaces and same- and reverse-written Arabic calligraphy create a syntactical interplay uniting the pieces. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        As a Pueblo potter, my strength is in my ability to work both as an individual and member of a community. In order to present formally developed artistic ideas, exercised through the visual language of traditional ceramic techniques, I use visual strategies and language derived from cultural myths and symbols, Native American and Pueblo ideologies and values, and Western and non-Western philosophies. My aim is the same for all pieces produced: complete artistic satisfaction.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Conviviality is the name of a gathering. I built a table of clay and wood, surrounding it with eight plates, cups and a bowl. Gourmet Subdued is about the forms that the gathering leaves behind. Food and drink are gone; the table and its iterations are left to delay and refine what have been consumed. The work is a celebration of the moment, the implication of what was consumed puts the aftertaste in the mouth. So life and art have many shades of meaning. I take inspiration from a high white mountain pass in the Monashee Mountains of central British Columbia. Occasional gatherings on the edge of a remote pass between the Pacific and Cariboo Valleys; it has been welcoming immigrants since the gold rush. The table will be waiting on the bench at that quiet location waiting for return conviviality.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The weather has been warm this spring and a single Robin has taken up residence. For Robin's return I have begun to harvest the imagery that is required to create dinnerware. As every food placed on the table calls for its own proper container my aim is to use the forms to suggest an abundance of renewal and growth. Adding new variations to the dinner table that mimics life's ideal as present by aspects of nature . Mixing past with a future abundance.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The versatility of clay offers the opportunity to release the individual from societal expectation of all that it stands for. 
        </p>
        <p>
        The history of the craft and its value come from the same handbook, however, it has rarely been accepted as being an evolving idea. By acknowledging this element we are now able to re-read the historical making of pottery with fresh eyes and see it for what it is, an invitation to creativity and new directions that would like to be explored. The opportunity looms to produce artwork, possibly sculpture, that is fundamentally the same as utility ware, only difference is the scale. 
        </p>
        <p>
        Teaware can be a place to practice the art of painting and carving in clay, to learn and extend the range of utensil, to allow for novel ideas of usage and artmaking. 
        </p>
        <p>
        By bringing functional ideas together in an individual setting there is the potential to create our own environment that has the prime consideration of us and the way we live. This attitude gives us permission to attach our own value to an object, freeing us of the restrictions of those who have previously done so mightily.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Humankind is challenged to make choices when designing and creating an environment for longevity. I have my own philosophies and conventions that drive my choices and decisions. The intended use of a piece influences every aspect of its surface – from decoration to texture and colour to shape. I’m motivated by the belief that a complete dinner table should contain three elements: utensils for food and drink, an equal range of serving ware, and any necessary holders for place cards and signage. The ensemble should reflect the mood and ambience of the environment it is a part of, whether it’s a boot-kickin’ barbecue on the back deck or a formal setting fit for the condo board; I want my knick-knacks and accents to evoke socialized use and a “How’s your Uncle Fester?” country club calm.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Fragments of colour - isolated, adjacent, side by side - anything so as to free the colour from the multitude, science, sense, science again and again. A world vanishes; now only colours. Purity in its utmost form, far from what we know as colour and from life as we know it. But the passion for pure colour has remained. It is, I believe, the only thing important about painting.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Coming from a female, I often question the dearth of feminine personalities in western art forms and the lack of women portrayed as even taking part in anything other then sewing, cooking and cleaning. I believe that art is about expressing our ideas, our emotions, and learning about others. I also believe it’s about the tangible. I have difficulty thinking that much made from a symbolic point of view provides us with longevity or any instruction of how to make our day to day life better. Perhaps. But our need for the Earth is immediate and I want to see a balance between the tangibles that will provide sustenance for our own Earth if we would only learn.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        In both their transparent and unblending ways, the vessels found in the Hudson Shore or the Americas or hundreds of years ago now arrive with the needs of modern man or woman. A man is not concerned with just eating or drinking, but he eats with his neighbour or drinks with his companion. That companion must consider an object as much as an appetite or taste. That companion must sit at a home dining table or a dinner table at an art gallery, it must complement or reflect the needs of that moment. ... What is to be expected next, how will this look?
        </p>
        <p>
        Our designs now come charged and excitedly aware of their fundamental purpose and intent. That excitement must then be controlled and cooled into stable, considered, thoughtful and functional objects. We are now here to stay, and to stay, and to stay. Though we might thrill each other in our hand drums and uncooked food.
        </p>
        <p>
        The exciting thing for us all is that there is no control as to what plastic and paper might give way to, and be lost to, in its coming forms.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        A functioning dinner table has been part of most social engagements since time immemorial. As a professional designer, designer/maker and devoted amateur chef/foodie, I find this subject incredibly stimulating. The table doesn’t need to be large, but it must serve a purpose to function and tell a story over time. Our “lives” are reflected back to us through the dinner table, which should be considered from time to time, what are our favourite guests, how do we want to be communicated? Will our mood lead to an informal party or time of calm to interact with each other over an exceptional dinner? How about the acoustics above and around the table? I love well defined “sound” and believe my sculptural and functional pottery to address the issue well.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My passion for pottery is a genuine part of my connection to the continuity of human endeavor and symbolizes a field of influence as a part of our current time.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        If words could describe the essence of work, my mom would rest on the grounds that magic, sanctuary and highest truth are the fundamentals of my output.
        </p>
        <p>
        Abyssal and monumental clay serves as the springboard of creation. Scorned and chased over 3000 years ago, it dominates through fear of its explosion. The power spawns symmetry and paradox, twin forces capable of changing the red clay into a virtuous product.
        </p>
        <p>
        Ceramics is like fishing or being in love: it is intimately private and yet profoundly universal.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I sense a commonality that weaves through the field of making things. In the hands of the potter, that which is familiar is redefined, playing with, testing and violating. Deconstruction leads to reconstruction. 
        I use a bit of scientific inquiry, but tend towards an analogue approach to my pots. What I look for are new perspectives, forms in the periphery and anomalies to drive my work. From my vantage point, the journey is never spurious. I see elaborate paths, complex and pragmatic inner dialogues, a variety of philosophies under one roof. The complex path leads me through drawing, where I play with form building a framework for the pots to come. On occasion, I follow a more literal path. 
        </p>
        <p>
        The making of pots is a metaphor for the creative process. It seems to me there is value in this wheel, made in stone, first in archaic Mesopotamia and today to continue to turn, still looking for the perfect pot."
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        “In shaping and firing clay, I like to depend on the incidental but also follow a set of rules. In this case, when building with clay there are just as many accidents as there are successes. It is the successes that I try to follow. Though I alter, omit or explode some rules, I continue to search for new rules or ways of existing within the rules set before me. I am currently questioning what are rules and what is happening in between what we call rules, what will be left as practice if we throw out the rules. By collapsing time through stratified and intuitive processes I lay basic forms that later will come together and intertwine. The transformation from basic forms evolves through sculpting, building, digging, cutting and burying. What come out of this are objects that suggest landscape, bodies, vessels, vistas and the unknown. In spite of how the work looks, the only moment it resembles is the moment it happened.
        "
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        A china pot is nothing but clay with a hole. A glass is nothing but a metal with a hole, simple as that. And it's the not the inside nothing hole, but the not the outside nothing hole. This "nothing", even if it depends on what you call, is the hole of everything, the truth, the rationality, the spirit, the fantasy, the absense, the mind, the ink, the water, the colour of all colour, the nothing with all the possibilities, the condition for every space/time, without condition. Therefore, the Middle Ages defined God simply as "OH" (as in "Big O"), which stands for Not a Thing. To make "O" possible, these holes had to be filled with simple materials to permute, transmutate and transmit the vibe to all kinds of phenomenons, in our present and in other planets. The Reality of a simpler vessel means to transmit an endorphinity, a first gnosis or inner spirit, so little that the body will be aware from that emptiness, the body can fill it, but not swallow it. Being an artist, I’m more interested about the awe of these spirits in the hole in the first place, and of the holes themselves, inseparable from the statics and dynamics, architecture and cosmology, or meta-physics and astrophysics. Over history, the holes have been here with us in a lapidary, animated way, so little that if one passes through them, he can be "plugged into" the energy of all the spirit persons that have gone before, after, and are possible."
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        "The artist has attained the highest plane of self actualization and the complete epitome of human potential. In the eye of the creative mind, no new configurations are to appear. It has become dull and insensitive to stimulation from within or without. The mot juste alone may be extracted from the dullard awareness. The creative mind requires total void. The peripheral senses remain the sole channels of information outside the subconscious. The foundation of the creative essence is a perpetual dichotomy between the actual and the conceivable. The entire nature of creativity consists of the primordial oscillation between the possible and impossible." Raymond N. Vezina
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My practice currently treats the dichotomy between ephemerality and containment – between the imponderable and the highly sculptural – between the intangible and the tactile. My work at any given moment of conceptualization is highly concerned with how the mind mediates between pure abstraction and surface description. What happens in the minds eye when confronted with visual phenomena, I’m interested in the phenomenon and in how the viewer interacts with it. Unlike the great analytical sculptors who work in three dimensions, I use wood, clay, concrete and my own body as source material to make modular sculptures and installations using a non-hierarchical methodology. The system of connections that are made between the pieces determines the space of the construction. The intentional incompleteness of the sculpture is an ever-changing, tactile experience of concrete shapes and spaces. Their work is derived from processes that creates objects and installations the outcomes are partly informed by social interactions and partly independent of them.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The level of craft and the amount of individuality and expression varies depending on what kind of pot an artist is making. I see two distinct differences: utility vs. decorative. Throughout history and in many cultures, vessels have carried many functions from ritual ceremony to cooking. Aesthetically these vessels are usually more restrained than their purely decorative counterparts; however, this does not mean they have less artistry. These utilitarian pots provide a context of their own. I am under the strong influence of earth, material, and familiarity – habitual behavior of some kind. Food is consumed here, moments are cherished here, in a quiet way it provides the stability and foundation of our being.
        This balance of familiar comfort and anxiety is an aesthetic I strive to achieve in all of my work.
        This body of work changes my ideas with repetition as much as being in their presence relaxes me. 
        When pressed for a pots genesis and purpose, one can’t produce any explanation beyond the presence of erosion. Rivers carve away, cutting their ever-spiraling paths, shaping the world beneath them since the beginning of time, eroding sediment deposited by Ice Age glaciers. Their path is as much a journey of the spirit as the physical travel of water across the land. I want to be present in that narrative, to give physical presence to something I have spent my whole life dreaming about. 
        Continued experimentation over the years has allowed me to envision a whole body of work continuing the current theme. 
        </p>
        <p>
        didn’t have a goal, I just sat down and did it. A few years later hundreds of pots lie on my shelves, inviting viewers to take them up and wander what they mean.
        </p>
        <p>
        I am totally obsessed with finding new, powerful and provocative ways to interact with landscape through animals, rocks, mountains, rivers, fields and forests. To me this is a whole body of work that continues to grow – breathing in and out of this same obsession.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Doing the same thing over and over again every day. I “see” it in my mind first then create it – thousands and millions of times. Not bored with the work… completely involved in exploring the process.
        Producing idea after idea always testing the parameters of the medium. A push/pull between limiting forms, process and materials and the opposite – to be unlimited by my own ability.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Pots mimic the art of conversation. When they gather together in a room it feels like they are engaged in a discussion, poised in negotiation with one another. Each moving back and forth in a way that suggests neither lead nor obeys the other. Their ambiguity reassures viewers that interpretation of their gestures is dependent on viewing context as much as sight. 
        </p>
        <p>
        The pieced-together aesthetic refers to the phenomenon of steel migratory work. Instead of people moving from city to city to find work, steel workers would often be laid off and move their families to another region where there was a steel mill. They would sometimes be laid off and move factories for more work, often settling in a different town where they would buy a house where they no longer needed to rent. This migratory work practice is formally related to how the pieces are put together in our traditional coiling unfired vessel, using whatever materials we have available to us, in the location where we are living and working, then with the aid of a kiln, fuse them together.
        </p>
        <p>
        We have moved quite a few times and for much of the work in this body I was making pots, staying somewhere for just a few months at a time. I move a lot and the pots I make become works on migration.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        There are 3 Visions of relief, 3 dimensions happening simultaneously with every stroke. One is the beginning, first stroke on the clay, a mental sketch, an abstraction, beyond words, like longing to connect, to touch, to enter into. The 2nd is how I clean up, or take away material to set relief visual elements into 2 dimension space while holding the space in relief. The 3rd, after the pot is bisque fired, I size and glaze the surface. The 3rd dimension is endless how I use the surface coloring and textures to inform the pot, emphasize a feeling, set light into the space, it’s texture and scale. As if it was a place, setting the stage, using color on the walls and ceiling to set a feeling. Think theater as in sculpture, not community theatre.
        </p>
        <p>
        Secrets are hidden in the relief, colors hide tension and hold the other areas in focus.
        The color accents and sets accents into the rhythm of the relief planes, visual/aesthetic and sensory.
        Areas of stress are revealed, maybe awkwardly placed, the backbone? Relief highlights and attracts a viewers unconscious. It’s light and free, kinesthetic, active and a kinetic feel.
        Work is significantly layered. The layers of activity, the spilling over helps hold each area in relief. Visual travel from one side to the other side fuels the interest in pots as sculptural objects. Some pieces will stay whole in front of you while others really need to be spun in order to be read – turning away from the image to introspect, decipher, process. Looks can be deceiving. Starts are slow, having a difficult time beginning.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Presenting work, showing 1-5 pots at a time is a concept idea that I feel helps me show my ability to manipulate different glazes and placement of them, depth of firing and color contrasts since I commonly associate my work with puppetry.
        </p>
        <p>
        It’s not the piece alone but the amazing space they recreate visually. I have a puppet background, so I manipulate my pieces like a show.
        </p>
        <p>
        I manipulate my pieces to signify space and place where they occupy, the ability to climb in and enjoy on a regular basis.
        </p>
        <p>
        The mystery of my pieces starts with the dark base construction, the mystery of having to discover the anomalies, what are they? They are always performing like a show of controlled chaos. My suggestion is the design of the piece is suggesting multiple ideas but at this time I am not giving up all secrets of my pieces.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Silicon, aluminum, and magnesium, elements known most commonly for their reciprocal roles as conductors, transitional metals, and vital ions in an array of organisms’ bio-chemical exchanges, have historically provided the fine potter with fluid vessels of varying degrees of conductivity and compressibility. Modern methodologies of the potter's wheel can be traced back to pre-modern cultures and technologies, which relied on prehistoric clay-lined fermentation pots and bread ovens to concoct silica material.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The sequential process of clay innovation is restricted to a moderate analog, but what technology has submitted in speed, flexibility, and efficiency, has in turn offered an amplified spectrum of compositional options. Sampling effects of electric currents, arching temperatures in oxidation, and yet greater transparency in firing speed - all in time and stillness - are in fact our liberties. Much like the dilemma of modern man, to predictably govern or naturally grope for control, it is insight through the colorless lens of perspective that mirrors a near century of electric spark.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Working from a tradition, derived from American studio craft pottery of the 1950s-1960s, my pots deliver a familiarity of form, material, and surface manipulations. Each piece is an investigation into singular construction techniques. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Single pieces are inspired by current events, memories, social meditations, geological data, museum experiences, family secrets, pop music, folk culture and other ephemera. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My utilitarian salt and pepper shakers exemplify how in a self-perpetuating, cyclical nature pottery can monitor and influence functional objects. By altering the scale of appropriate production methods and focusing on the intrasnse quality of hand made I alter the context of ceramics in our daily lives. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I am interested in how my individual choice of materials leads to effects that can be explored and, to some extent, predicted.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        For the past several years I have searched for ways to compose forms, volumes, and surface qualities into an emotional and intellectually coherent response. Many works that look like round bowls start out as square pieces of clay, others as a tunnel of clay, pressed out under my feet while standing on a sculptural form. These accidental forms are stored in my memory.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I make decisions about what to discard or repair based on an intuitive desire to move a work through to completion. I am attracted to the impermanence of a material that also has a memory of its history, making studio work a unique opportunity to allow accidental forms, happy accidents, and planned events to accumulate into a type of storytelling, each piece providing a narrative of my time here on earth. Due to this accumulation, no two pots are alike, when they keep their memory. They all have an aura, and with each additional firing over time, the aura changes.
        </p>
        <p>
        My research into the properties of clay and glazes has been ongoing for the past 25 or so years using cement, fabric, glass beads, found objects, wood, paper, plastic, and naturally occurring objects to alter the surfaces of my pots.
        </p>
        <p>
        To create two- and three-dimensional works, depending on the interests of the project, I apply wood and gypsum board, using glues, screws, nails, water jets, brackets, and threaded rods. I continue working on my wheel from time to time. To strengthen my interest in the narratives of time through making, I constantly find ways to build up and decompose clay materials to show the impact of time. My studio is dusty with silt and clays from the past as much as with glazes of the present, and from time to time I have been a contributor of the fine dust that creeps everywhere in a studio practice that is committed to reduction. The surface of my reference group and heroes of art and design contains a gritty patina, as all who work with material, whether new or old, cannot avoid the residue of an immediate past that is written in the material, the scars of use, and all of the accoutrements of a life spent with hand and heart in relationship with the materials and tools we call upon to make visions.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I make primarily sculptural vessels and objects that exist in the social space that most people occupy. They can rest on shelves and in cupboards, but it’s the behavior of the body that creates their primary existence in my work.
        </p>
        <p>
        My driving is that I'm trying to understand the somatic nature of creating and the utility of that experience in my life; how it affects the way I walk around and interact with other people. The physical sensation of doing some-thing is something we all do, but the object that gets made is a product you can hold in your hand. 
        </p>
        <p>
        Wheth-er the works are cups, bowls, vessels with lids or handles or made out of wood, it’s still a physical sensation to hold these things in your hand, pick them up and hold onto them. So I make these things to distort the experiences people have when they hold something in their hand and hold onto it for a prolonged period of time. I distort those experiences, and I distort the objects that people hold onto, because I don't find normal everyday use-ful anymore. I feel that it's an opportunity to break some of the normalcy and use-fulness patterns of objects and come up with other ways of holding things that people might consider.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Prior to focusing entirely on my training and development as a blacksmith, I worked as a director, potter and visual artist. Now most of my own artwork has evolved out of the clay fields where I located myself, taking questions about the nature of clay and the methods of testing. Objects are made to reward beautiful symmetries in rows of bellies and coils; they invite natural straight lines into objects that nearly always take curves. My thorough investigation of wire also allowed me the freedom to design emotionally. My raised non-functional barbells and rings recall the protective enclosure of bridges at night. Other wire pieces named for markings on golf courses and tennis courts include surfaces with details mimicking the clean patterns of ball-strips. Swinging back and forth; objects flirt with tension, readying to break. The invitation to take (as the objects themselves take) the long elegant arcs of circular swings, more common in recreational fields than clay ones, will leave the viewer while contemplating the means by which something sturdy might exist in a state of exuberant openness. This fragile suggestion is further emanated from minimal gestures just under the surface, and from the fractured, inorganic planes of glazes.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Anticipation is a lean in the flesh, warm hand on cool tile, an eye on a wet bowl, hoping that moment the warm glaze hits the wood fired clay, or the drips begin their downward fall… these never failed epiphanies are the reward of a day’s work. This is where the art emerges.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        While potters may possibly choose to exhibit the series of their choice, I like to exhibit all of my current and past work in a continuous narrative of my time in the studio, balancing the desired social space of a home with that of a gallery.. Language in the studio for me is also an exercise that begins with the clay and fire. It is an investigation of the language of clay in terms of its expressive possibility. Identity is a very present notion as well. My work explores all senses of the male and female archetypes in order to include them in the narrative of contemporary pottery, expanding the definition of what pottery is in relation to art and activity. I am interested in the fact that our inner selves are often in conflict with what we do and say publicly in relation to ideas such as the homemaker/career, the male and female roles, and societal expectations. I attempt to address these concerns in art and photographs that range through time. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        In the MA student studio, we work within The Earth is a Factory School. The phrase was coined by my professor Paul Soldner, maker of large scale earthenware assemblage, incorporating elements from the wilderness where, at the time, UCLA Extension was situated in the foothills. After moving to Hampton, WA, The Earth is a Factory School has expanded to include the Coast Salish people. Their world relies on water for life, and provides a window for organic investigation of process and time. 
        </p>
        <p>
        In recent work, observation has led to relationships with sources that surpass "interiors" observed in mass production and manufacturing methods. Observation outside of one's own perceptions produces valuable data in both imagination and process. The material world is an open book for exploration of relationships with clay, nature, traditional craft, and methods of making. 
        </p>
        <p>
        Characterized as life-size, nature-mimicry, and abstracted, I assert that my flat-woven baskets are earthenware vessels that offer an organic language of self-identity. Streams, creeks, rivers, springs, beaches, tide pools, shores, and mudflats are frequent destinations along with land-based fieldwork
        The frameworks used to support two-dimensional wall work are fabricated of black willow. 
        AN INVESTIGATION INTO THE MEANING OF POTTERY IN CONTEMPORARY LIFE
        The importance of clay in cultures everywhere is vital.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I like the idea of developing a lexicon of forms built up like archaeological excavations, and then chipping away at the underside of the vessels, revealing something of how the vessel was constructed, and how the forms inhabit the space of the vessel. I then overburden the top of the vessel with additional planes of texture. This occurs because I believe it is important to create vessels that are a hybrid of the familiar and the uncanny and the familiar should not predominate.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I'm driven to make these welded oxidizations as a response to grief and loss in my life. Currently, I work in an electric kiln with a very intimate yet volatile process. I am tethered to these otherworldly combinations of the abstracted. The work draws huge amounts of transcendent heat while shielding me from it. I work with a skilled balance of self-consciousness and rigor. I want to put into the work some abstracted memory of death and resurrection, to deploy it as a talisman of how rich and disturbing a life can be.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        "My art is a journey into this world and this world's future. The theme of my work is light and shadow, hope and doubt. I seek to strengthen the human condition through my work and the emotions with which it is felt. As with our lives, little that I make can be defined into one way, and I like it that way. I want living viewers to question what they are thinking as they look at my work. I might like it if viewers miss things and ask the questions that I miss whenever I create something. I want pictures to provoke thinking rather than provide explanations. I hope that those who view my art are able to relate emotions and thoughts to things that they might read or have been taught or create themselves. I also like visual confusion in my art, as I don't like to be only understood, but rather be left in a state of continuous thought.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Context and belonging are key factors in the work studied or produced by any artist. The potter's wheel, the imprint of hands, the textures of tools, the crafting and creation of pottery, are mediums that revere many cultures; the culture of cuisine or houseware, utensil or sculpture. If we take a panorama of a household and stir in the element of history, then live bodies and emotions, currently-used items and then one response to an existing style or form would unfold at a larger scale on a global perspective. In my own journey of hands on and hands off interpreting statements and questions from a whirlwind of cultural influence, continues to be an opportunity to grow and change with every project I launch. This view, beyond that of other potters, has and always will be in my work, my creative being and an identity that marks me belonging to the world community. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The stacks of thread spools, buttons, hinges and other found objects, imply a whole host of disjointed gestures acting independently of design. They are the outcomes of intuitive moves, rash decisions, and on-the-fly cohesions. They are numerous, disparate, and a smattering of things that define a particular space, but are otherwise thought of, only during the act of creating the art. 
        </p>
        <p>
        What began long ago as a ten-year mark to reflect and signify a point of contemplation, quickly morphed into a twenty-year mark. Each year approaching and passing, proved to be a complex melange of texture, simplicity and complexity. Each year was and is simultaneously a reflection of the past 20 years, as well as an omen to the 20 years that will be. 
        </p>
        <p>
        Beautiful patterns and shades of color that arrive from the inherent energy in any given color formed from a juxtaposition of off-the-shelf and prepared paints create works that stand alone and unexpected, with a sense of momentary flight as they enjoy space within the maze of time.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I love to explore how pottery connects with people; while the tangible strength of the material is mesmerizing to me, I find the resilience of aesthetic form and the versatility of the maker to be the compelling factors of human relationship. I explore the transformative nature of ceramics by playing with multiple forms of pottery practice. The tactile manipulation inherent to throwing, handcrafting, slab construction, and traditional coiling, are evidenced in my work alongside a new discipline showcasing stoneware clay-on-clay construction with hybrid stoneware-terra cotta glazing and wood smoke through traditional shino and kuro shino glazing.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Constantly aiming to reinvent myself and my work, I combine the potter’s individual physical and hand skills with inchoate subterranean forces and processes perceived through time, thoughts, memory and tell tenuous personal symbols of emotional response to my immediate experiences. Beneath microscopic fingerprints lies the story of my life and the life of my context, ultimately revealing a story of self and identity. My textile practice offers a freedom associated with an individual’s personal expression, without the constraints of functional utility. Conversely, my pottery expresses relationships between an individual’s want and need states, the pleasure derived from form and texture, the complexity of climate, and the restraints placed on form and function by nature’s forces. Hence, my work represents a maximalist point of view; from a Minimalist’s perspective to an Individualist’s point of view to a statement beyond discipline, process and production.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I draw inspiration from daily life, both my own and other's; contemplations of the natural sciences; the imagined "condition" of objects; myths, stories and folk tales; my history reading and research in art and my investigation into the geology and physical science within my home region. I am grateful for my archaeologist father. By investing history, time, excavation, and care into the acquisition of our own particular collection of artifacts, I find in the narrative of old artisans and the elusive tools they employed, a host of metaphors for the way I work now. I use the ordinary, the gash, the shiny, and the mundane in my work. I am fascinated by slop, fog, burl, fawn offshots, and the diversity of gases – I call my methods Methodology In Glaze and Creation Vessels.
        </p>
        <p>
        One summer I noticed how the glaze I most had a hard time fusing, a transparent frit, held glaze on the undersides of tea cups where as a transparent engobe, it scorched like a crop circle. Abstracting the implied dusted surface of a cake and the massive weight of ash, I am always looking for and grasping for this distinction. Reflecting the energy invested its making back into it and the world - a literalization of our deep connection with the natural sciences and human events - this backflow or "scratchback" puts a personal mark on a pot. I live on a rural road in Southern New Hampshire, a place where farmers still follow the patterns of the Moon and weathervanes align; I am inspired by watching the cycles of the night sky, by seasonal changes, by my community of friends, new and old, and by geological anomalies right here at my fingertips. This all spins up my own stories, which I speak and lay down traces of like a comet over a celestial map. My passion is for this dialogue of spinning a body to ice: to make it in a moment, fill it with a year's evening work, and have it last a lifetime.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Porcelain: technically very pure, translucent and nutrientless, only man-made material to successfully imitate natural (quartz) crystal in clarity and brilliance. It freezes liquid bones, dissolved minerals from fire to make glaze fawn thin, veins, clear in lime, melding smoke to body in porcelain hearth. Requires highly refined mineral parts:
        </p>
        <p>
        Curiously harmonious mixture of a more nascent fauna than mineral, organic earthy (like filled bark, fibrous) porcelain fossilized aura, alchemical process of fire, water --inherent, architectural, static process, waiting for nature in/of glaze to ransack clay casing clots upon glaze rests. Takes time, skilled workers to master carefully controlled manipulation of this flesh and bone --extends life by beauty of imperfections, one from dust accepting of entropy/addiction to beauty of impermanent tools. Porcelain’s matter broken by distortions, scars, rings, flu resist glazes spiral earth limbic calcite, lava scape in/unaware endless water movement, eternal sprawl, crystalline dreaming, intentional mark waver/trembles air/porcelain less joint unbroken criticality delicacy /gossamer haze/smoke/water---constant accidental constant combustion controlled incomplete magical inner body exposed shape/decorous manners/morals in peril make and use small daily ceremonies until all are ‘did then’s’ ransacked bones into lacy/gossamer minuscule. --Kate Rushton
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        There is growth, and maintenance, of life and death in the make of this body of work. Constructed, and destroyed. Organics, and non-organics. Woven, and webbed. Stoic. Sculptural, and slump. Dazzling, and ash. Glassiness, and flame, blinding, beguiling. Soft, and hard. Must have form. Apply outside forms. Bring inside forms. Seal. And crack open. Primary and secondary forms. Edges. Soft edges. Bold edges. Polished. And un-polish. Stains. Impact. Saturations. Deprivation. Broaden borders. Strict guards. Envelopes. Rootling and Treeing. Seeking. To plant. Root, and blossom. Set surface. And lace it, insulating inside. Crust. P&B. With overtones. Lightness. Air of. Between breaths. Breath into it. Breathe out of it. W/pressure. And hollowness. Smells, and smells. Bonded, and un-bonded connections. Alive. Excitement of. Of. Unveilings. Second chances. To make again. And again. With material. Skeletal. That requires. That needs. That is. Aware. And conscious. Welcome to. Belly of. And muscle of. My. Skegg & Jackson.
        Look up over handle. Of cup. Ask: What fathom. Basket do I live in?
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Contemporary ceramics have been strongly influenced by eastern philosophies and the principles of Zen Buddhism and Taoism. They focus on reduction in form and design, especially in the area of decoration, striving for unity with the simple and the elemental in a reduction to the absolute. Although I do not practice reductionism, these philosophies provide mental direction toward what has become my main interest, the direct connection between the vessel as living space and the vessel as vessel. These vessels are intended to be natural extensions of everyday life, for each person to live and grow in, therefore, the form and function must remain consistent and matured.
        </p>
        <p>
        In my vessels, the norm is to wear over time. While the body of the vessel could be convoluted into the traditional form of western ceramics the surface and the glaze, are different. The earliest surface application in one of my vessels mimics a pattern of randomness. This is an intentional presentation of frosting. Over time, the frosting disappears and the surface matures. It breaks down from a flat surface into a more textured form presenting character and introspection. Glaze settling between surface and clay also creates the same type of uneven textured surface. As in life, the vases are not perfect and therefore must mature. This process keeps the vessel and myself interested visually over time. The aged surface is also broken by techniques such as piercing and carving. Both penetrate the thick and tough surface. These scars are another part of life that add to the surface maturity and visually adds another quality to the vessel. Scrimshaw and zinc pedal paint are also ways to modify the surface. These "happy accidents" create more interest to the surface and create a more sensual space.
        </p>
        <p>
        Contradicting the east Asia philosophy of the plain and simple, I found by carving the surface they are the opposite. They are better, more interesting and alive. The organic shapes are a contrast to structured forms and a juxtaposition of casual to fine. As someone who enjoys the mystery of life and the boisterous stages of development, I want my vessels to convey that enthusiasm while still being fashionable. Vessels that have matured, cracked and had the surface beat up, now become charming. They are even more alive. The contrast of visual and structural severity, contemporary and historical, pretension and folkloric, allows for another simultaneous consideration. This structure and surface contrast helps to show how this space was built upon small ideas, hope and chance, all contributing to the building of this interesting outcome.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I create surfaces for contemplation. 
        </p>
        <p>
        Depositions, gray and black shades melt, dissolve and form pools. 
        </p>
        <p>
        Water is spilled into these surfaces, testing the strength of agate’s smooth surface. 
        </p>
        <p>
        Shattering and shifting push and pull these surfaces into saturated tension. 
        </p>
        <p>
        Planar tension wedges inward: pushing boundaries of surface and shape. 
        </p>
        <p>
        Saturating the vessel substance, the body of the vessel. 
        </p>
        <p>
        The natural impulse is to press against the surface, to embed within the form.
        </p>
        <p>
        Pressing in a confined space.
        </p>
        <p>
        Substance over saturated. 
        </p>
        <p>
        Soaking already wet. 
        </p>
        <p>
        The vessel has shifted planes causing a rupture in its structural integrity.
        </p>
        <p>
        Fractured into many parts like the potato. 
        </p>
        <p>
        When fire bites and pulls to explode these parts into freedom.
        </p>
        <p>
        Vessel of failure.
        </p>
        <p>
        </p>
        <p>
        Like the potato. 
        </p>
        <p>
        Burning. 
        </p>
        <p>
        This sculpture is ready to return to the composting.
        </p>
        <p>
        The rebirth of ceramic art.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Autumn's Vessel is a rustic, utilitarian form composed of multiple pieces ceramic. Specifically, it is a prehistoric and ancient shape for the storage or gathering of food or life providing sustenance, and a weight for precious commodities.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I find elegance though paradox, roughness or contrast in the contrasts. 
        My work expresses the cultural concepts of inner and outer, up and down, with a focus on the interdependence of form and surface to create an aesthetic contact with the viewer. 
        My hope is to humanize this interdependence, lending to understanding through the mirroring of expression. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Contemporary ceramics
        </p>
        <p>
        is polychrome, critical
        </p>
        <p>
        and reflective of our global
        </p>
        <p>
        culture. While acknowledging
        </p>
        <p>
        traditions from Japan, 
        </p>
        <p>
        China, Italy, England, Turkey
        </p>
        <p>
        and the United States, the
        </p>
        <p>
        decorative arts are political,
        </p>
        <p>
        progressive and poetic. Ceramics
        </p>
        <p>
        is an art of play and a
        </p>
        <p>
        humble acknowledgment of our
        </p>
        <p>
        inherent fragility in the midst of
        </p>
        <p>
        such destructive forces as fire.
        </p>
        <p>
        Artful ceramics embrace
        </p>
        <p>
        stylistic diversity, historic
        </p>
        <p>
        research and intellectual
        </p>
        <p>
        pursuit. Ceramics is the art of
        </p>
        <p>
        the fortunate, educated and
        </p>
        <p>
        informed. Ceramics is a play
        </p>
        <p>
        of maturity in an enchanted
        </p>
        <p>
        world that keeps us
        </p>
        <p>
        informed and intelligent.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        When I walk, I draw. Drawing in the landscape is a personal and meditative act that extends the composition of the whole and offers a starting point for paint application upon returning to the studio. The environment triggers an emotional response and references the day’s experiences. The landscape observes our evolving culture while remaining consistent. The drawings are representations of feeling and experience, the maps, charts, and notes made of effects rather than details. Consistency of basic line, color and drawing structure allow digression into visual motifs that explore ideas and formal design. Visual rhythms, compression, division, contrast and transition provoke emotional responses and evoke memories and stories. Space discovery, surface, hue, value and patterns are used as vehicles to express meaning. An image is inevitably woven into the drawing that exposes a state of the mind. The mind of the artist remains in the process and more importantly within the final compositions. These works are studies of observances and connections that explore the essence of humanity through basic emotions, the invisible and the common. A lasting breath envisions momentary fusion on a journey that transcends time and space...to her!
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Glaze defines surface color to the final drying stages of clay bodies, while clay itself remains the principal body manifesting form. Each new body signifies a language of clay where linearity may be broken, slashes and drags of clay gestures temper turbulent steel-toned surface information, while fired sand applications push the fray of the discussion beyond the vessel.
        </p>
        <p>
        Awareness of glaze chemical makeup along with color and texture possibilities builds a dialog between glazed surfaces and vessels formed from the interpreted and translated poetry of clay at the moment. These conversations encourage nuanced decorative decisions that emerge from varied methods of working with paint and glaze, while refined printing methods of stencils and slips enhance the dialogue. Through combinations of slip, glaze and paint layer upon layer of surface information creates a unified installation of decisions and gestures interpreted by hand.
        </p>
        <p>
        Side-by-side or staggered rows of clay and glaze questions the ideation of surface. Alternatingly droplet shaped clusters of clay and condensed paste sequences expose sublime micro textures. These surface gradients push and pull upon each other, section to section and bowl to bowl, using color and texture to sculpt excess. The poem in clay stays close to the earth, feeding off soil, minerals, water and sun. A new body offers a momentary resting place, before hurrying along it’s way for another material form to fill. 
        Equally, when careless touch, pavers and trowels, brushes and brayers, stencils and prints, all busy together on a surface push and pull too close to each other. Harmony arrives in tactile curiosity and the curve of a vessel reveals itself. Demur to the moment and a tactile excitement awaits the hand to smuggle into the world. 
        </p>
        <p>
        My touch lands materials on surfaces and in this series it must remain. Process of layering and slivering is encouraged from the near liquid to the dry slurry. 
        The opening and closing of vessels creates new opportunities for interactions of glaze and clay. Continuing to build and accumulating glaze surface, slipped surfaces assume a new light awakened to spatial explorations. 
        </p>
        <p>
        Pattern is appreciated but openly controlled and manipulated. Resisting restraint, the hand and mind find happiness in the slip across a glaze and the resulting tone of the space created by the touch, and is happy enough not to know which came first. 
        Strangely, the accidental coincidence emerges and is stronger for it’s serendipitous arrival, and serves notice to a world whose talkative gestures and quiet whispers are signs of a common language.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The program is suggested through the material, limiting to two bodies, two different clay bodies similar with transitional material includes dish and slip, a translucency and an opalescence. The individual entry components are similar in scale, necessitating each to engage the other. The silhouettes are individuated through a series of volumes. The smokiness of the upper smoke flap and broad overhanging roof are balanced against the vertical industrial look of the pipes at the platform seating area. The counter of the part of the tower seen at the entry end of the building is the root of the interlocking delicate reeds which “grow” out into the main area. Each vein on these is accentuated, the skin becomes thinner, and the vein branch wider as they develop outwards to the exterior walls at the canopied seating level in the large area.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Ceramics and painting have been grouped before as well as still are, particularly as the rise of ceramic painting occurred simultaneously with the rise of modernism. Although each discipline is born from fundamentally different traditions, their marriage seems logical. Both involve pushing two-dimensional material into complicated three-dimensional forms. And the surface is an operative feature in both media, although it functions more like a crucial interface where interactions between material and physical context take shape.
        </p>
        <p>
        However, there are significant differences. While painting is fluid, spontaneous, and one of the last remaining free creative powers available to mankind, ceramics is mechanical, systematic, and bound by materials and techniques that seem scarcely spontaneous and prone to the course of convention.
        I have been working with the metaphor of the painting within the constraints of the ceramic medium, throwing down and building up multiple colored pinch pots. Occasional brushes of slip, layer of glaze, and braiser flash have allowed more painting creative directions and results the way using transparent watercolor transitions on paper or wood might, a glaze wash allowing more paint decisions, etc. The result has been throwing each paint color separately, one by one, and allowing each throw to fire. After about three firings, the colors normally reveal themselves in a triadic set of ragged interplays between cool form, muted undulation, and screaming dense black/white and the associated set of colors, evolving over time. This is a discovery process. The whole interval from initial matching of each of the colors, to the final revelation of the set of colors, is roughly the same length of time as I would devote to making one large color field painting in oil. The throw, fire, lever, open up, throw, more fire, more clay, open up, more clay, and on and on for several centimeters, could last a whole day. Then you focus and see it and work it through to a satisfying end.
        </p>
        <p>
        Now how to get people to attack, manufacture, glaze fire, polish, glaze, kiln fire, to 14 highly technical steps, three days, thousands of hours, for 35 dollars a vase using the throw and fire method? The technical issues are staggering at that level of financial commitment to labor. 
        Artists are beginning to embrace this approach that comes from the attitude of “making” rather “painting.” And, a new series of challenges and discoveries in making is stimulated through the trade-off of limitations of the thrown form itself. I get tremendous pleasure form this approach. Its difficult. I envy the casual approach and choice of material, brush type, and variety of materials that oil painters have available. However, not only is there wonderfully subversive appeal to the stripping away of contemporary glaze culture, but it opens a range of throwing and altering that is unique in ceramics and a source of endless fascination.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Ceramics and painting are analogous in a respect in that they follow models - rules that govern the construction of their subjects. Their procedures are similar in the way that one begins with an idea primary or an element, and continues to build from there. One knows they have finished a painting when it feels finished. However, they are radically different in the sense that one is purely visual in its cues, while the other has both visual and functional characteristics. The paradox lies in how to convert this from a useful piece to a form that is pleasing to the eye, or that flourishes from its inextricable ties with function. I want to push the limits in which I push the roles that pottery plays in our lives. I feel it is my duty to communicate the abilities of this fleeting form to provide our food, drink, and enjoyment for us to remember the agency it plays in our lives. I would like to punish the pot with the same prestige and hardness as painting, but still end up with something that is socially legible. A Bετος is a pot piece that negates its practical use and at the same time intends to pretend it is a useful object. Its form is a prop to remember to visit what is fleeting.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        "I created pots as an act with these gestures.
        </p>
        <p>
        I will create again with these intentions.
        </p>
        <p>
        I molded it to bring forth what was dormant. 
        </p>
        <p>
        My hands sculpted it because there was room."
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My fascination with ceramic vessels started when I was in college, making sculptural pots without feet and bases. After digging around at flea markets, yard sales, antiques shops, and my own grandma's stuff (who loved pottery FROM there to China) I turned an early passion into a love. I now find it impossible to let a year pass without making at least one pot. You can't believe how much you can learn from a piece of clay. I particularly find inspiration from ancient forms of ceramics - from Chinese rice bowls to Hopi Pueblo to Mayan. The craft of ceramics has long been about storytelling, so my pots reflect these stories. I love how a break in the surface tells the hero's journey of a story in a pot. It is a history of acquisition and use as well as a projection of one's reasons.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I look for my ideas in things that live within not far from us. Everything here is beautiful. I look to country life where we are. Beans are in the fields have been in the evening and morning. A bubbling brook across the road. The nest by the china barn and the china barn door planted with daylilies. There is no need for of far flung black and white and shadows of gray. My world is fluorescent and full-color 3D, flora and fauna. As I spend most of my time here I to take away the worries and to support rural life.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I view ceramics and painting as two sides of the same media. Both have innate capabilities of symbolization and representation. Glazed ceramics have traditionally functioned as more decorative than clay. On the other side of painting, the medium will unite with the information of painting. The symbol form an interesting intermediate stage between two major forms of communication, glazing ceramics. I use the clay and glazes not only to symbolize mark-making, but also to charge them with the secret breath and nub of imagination. 
        </p>
        <p>
        My clay starts with strong taste of dirt. In order to interact with the natural ceramic materials, instead of fighting, I adapt to the ceramic materials. For clay, I search archaeological brushes, dung mud, and nothing is too dirty. I have to treat these “dirty” things for designing cups and jars. The base of most of my works is traditional casting process from natural clay either from South China clay or North china clay.
        </p>
        <p>
        The main reason for applying glazes is that my intentions are not in depicting the images, landscapes or flowers, I want to achieve my own aesthetic intention and initiate my imagination. Glazes are the final layer of work to symbolize the mark-making of clay. There is an evolution: first the surface of the clay, that's why “Only Clay can hold my breath full of silence”; second glaze poured on the clay is the color membrane of the hard surface. And third is painting. I paint each piece when dry after the glaze set, has been picked up the pigment from the floor of inspiration to the pieces and here vessels are separated from the real life. They are symbolic and are associated with contemporary living. Them are about information, communicative, rather than containers or forms.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        When the unexpected and absurd join the expected, each reveals the comically absurd, and I’m able to transfer it onto the ceramic form. The inherent plasticness of clay becomes my favorite tool for provoking the bodily to reenact awkward life through the expressive power of clay, and the ceramic form itself becomes imbued with complex humor. Unmasking the core of each form exposes a bumbling spirit in clay — humor. I hope to expose a new ingenious relationship between object form and bodily predicament, human and air. In all it is to overthrow the prescriptive, a serious and pedantic attitude, to reform the studious evolution of ceramic forms, and to create something playful with a dash of “everything or nothing” — a simple and joyous stance that goes against the grain of etiquette, tradition, and predictability. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        By mood and feel, I am very attracted to the influences of the cultures and people I encounter in my travels. They become a part of me for the time that I am there. I can’t wait to come home to make them a part of my imagined world. Working with clay has elements of slowness and time to accompany the revealing question, “How do I say what I believe?” I use shape to communicate harmonizing a tricky relationship between the ceramic object and human scale. The surface is another place a conversation may occur. In my case the appearance of easy command may belie multiple failed attempts and many happy accidents.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Though a variety of materials have been utilized throughout the history of ceramic sculpture, clay has proven to be durable yet malleable enough to be flexible to the needs of the artist. Redundancies found in nature such as rock, wood and grasses form the basis for almost all sculptural works. Layers upon layers of carved and thinned deep lines and grooves are added to the surface gives sculptures an illusion of depth and texture that becomes important when having the piece in stark contrast to a wall or on its own. Color is usually added in small controlled doses and always in a way to compliment the overall composition. Pieces are fired in an out door clamshell kiln. Glazes and slips are tested on tiles to ensure commitment to scale, form and function. Pottery is the heart of what I produce so it represents the majority of my work. My figurative work attempts to capture the depth and tactile sensitivity of my pottery by re-creating the curves and lines applied to my ceramic animals with clay collage on found boards.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Pottery is a tangible representation of memory that represents both personal lives and public histories. My core artistic inquiry is seeking identity through memory and community through my artwork. As a child of Vietnamese immigrant parents, the act of making art was for me the process of carving our stories into the memories, both painful and poignant, of my family’s journey into understanding what it is to be American. Art making has allowed me to understand the relationship between my sundering individualistic American consciousness and my collective as an integrated American culture. My works often reflect imagery and artifacts of refugee camps, and testify through their participation in public spaces the disconnect between our cultural values and actual conditions for immigrants. In tandem with critical debates about the current state of American identity and values, I am also interested in using the visual language of ceramics to express my search for personal identity. Utilizing ceramic ancestry accordions as symbols of my female-to-male transition from Miwa to Edwin Fennell made and included in my work seeks to be a body of work that raises awareness of representation of gender identity through material indexical representation.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Rowan Donovan combines an interest in natural sciences, detail oriented design, and an intuitive appreciation of natural form driven by vivid organic color. My earthen depressions are an exploration into the principles of abstraction, rather than the objects themselves. The act of collection is not so much a part of the process as it is the visualization. Working with transparent and translucent glazes is atypical of the ceramic process by which I’m interested in a particular sort of echo that only becomes clear by some small amount of distance. Continuing to look at the work and continue to remember is a necessary part of this work. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I work with historically ceramic formats (throwing, handbuilding, and slabbuilding) and surfaces (slips- underglazes on semi-transparent terracottas, and ceramic-asbociated uses of colors, textures, and surfaces) rejecting a thematic approach to an actual and engaging ceramics studio practice; I make ceramic compositions with a meditative dimension that integrates automonumentic visions from years of engagement with grand texts, myth, oral stories and dreams. 
        In recent years, I have explored elements of glazes, slips, under-glazes and specific on-glazes, searches for the limits of ceramic mediums and surfaces, and consideration of the ceramic as contemporary sculpture expand my notions of ceramic materiality. Extended from the notion of ceramic-as-decoration, I integrate this practice with a surface/object systemic language. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My ceramics are primarily hand-built, and feature complex layering of slips and underglazes, as well as natural materials and glazes. Through brush work, layering of organic materials and slips, additions of hand-formed interior “sculptures” made from local native clay, and hand-placed glazes either to expose layerings, depths, and voluptuous curves or tones, I want to convey the thrill of the process that is a big part of what I find exciting about making pots. More than wanting to create celebrations over a cup of tea or inspiring a meal, my pots are about a storytelling that goes beyond their functionality to communicate the narrative of my experiences from the places I’ve travelled and the studio I inhabit. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        “Ideas are all well and good, but the question remains whether they will translate the same way in three dimensions. Are these ideas strong enough to survive the translation? The physicality of it all is what intrigues and motivates me. I’m forever in a state of investigating and dissecting. Or, rather, being incapable of internalizing a concept and grasping it all as a whole so I spend cheap prices on the pleasure of eroding materials. That is the secret, to keep it simple. This concept is something I still fight with almost daily. Simplicity can be an elusive thing in this world of details. My work reflects on how a simple idea can inform so many concepts and thoughts. Through this I am constantly amazed by the potential of the things around me.”
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        The pots I make are liberated from preordained forms and functions, accidental, altered and altered again as they change materially and psychologically throughout their life spans, behaving like viscous, misunderstood teenagers. They resist categorization according to time, place or circumstance, symbols on their surface and casting vary at once, some small stories animate their surface. Worn by the hand those seeds will flourish; sutured to their disparate origins, continually evolving to self-discover.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Obviously my triffid-shaped pots are humorous and satirical, frequently depicting facial expressions, animals or human beings. These mixed feelings stem from the fact that ceramic is a nice material to work and on the other hand there is the feeling that it is a bit cheap or old-fashioned. So, for me, the pinch pots are also not too high-class. As a reaction, I produce those exaggeratedly nice and refined pinch pots. They may be comical as well, but have something in common with the refined double flowers of former times.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        My pots are narratives of contradiction: furniture seems to careen off the wall and, at the same time, lean into a hug. Plates seem to hover an inch from the table. Pots are insistent and demanding, and yet gentle in how they inhabit our lives and table settings.
        Their stories involve searching. Not for truth, nor answers, but for lines of dialogue and a deeper sense of our common ground. My aims are to create tools for the discovery of beginning and ending and the play between the concepts.
        Custom design or place setting for friends.
        Work that I have created specifically for company and community in my studios or rented studios, never for sale.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I make pots in diverse scales. I like detail and scale relationships that challenge an audience and seem puzzling in their arrangement. I find the contradictory ideas of fresh yet intricate, familiar yet obscure, alien yet safe in three dimensional form irresistible. My work is narrative and actions are contained by the space boundaries you find on a tabletop. Primarily my stories deal with home, identity, and culture, friendships and relationships. I gained the confidence to take this in another direction after class by leaving behind the confines of the figurative and being confident to move my work in any direction I wish.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        In general I like to carve thick and build up and sand molds and build up multiple layers of color then carve down through all the layers to around a thousand grit then use many colors and pounce all the legs and handles. My biggest struggle is finding a way to make my wood-fired pots presentable. Their size leaves me with choices of making them more decoration like or having to create that dramatic band around the foot that drives a conversation and makes them decoration like. 
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        I use clay as a paintbrush and wood-fire as a paint-dryer. I create fluid compositions conjuring images of space travel, sci-fi comic book influences, and futuristic visions of space. My pots are treated as they are manufactured. Not like an item of utility but rather like a culturally important glimpse of human creativity. Each piece contains origins and marks of its own specific surface finish story.
        At a point in the continuum between corrective and compressive repair, the surface turns into a seductive substrate of possible invention. The molded and cut forms abound in accidents and unintended visual reactions, becoming meshed into a significant surface event that offers unexpected surprises.
        Surcharging via structural collapse results in a visibly dramatic demarcation between an initially recognizable form and its final resolution. The glaze creates fluidic surfaces animating above and below its surface plane. Surfaces against colors suggest illusions, leading to illusive infinity. Benday rhythms are a compulsive drug. Treatment through function is fundamental. The visual imagination of possibilities keeps molten clay in motion.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Counteracting traditional European design principles, I attempt an open inquiry to deliciously formless shapes by playfully reducing domestic and food service vessels to new levels of functionality, minimalistic elegance and conceptual implications.
        </p>
        <h4 class="title is-4">Artist Statement</h4>
        <p>
        Using a minimalist approach and through a series of modifications and critical thinking, I investigate how ceramic form can acquire multiple and articulated functions.  My approach to the work undermines a historical conventionality and instead cultivates mindful connections to ancient cultures and a balance between cognition, connection and action.  I strip each piece down to its bare bones, reflecting a value and criticality to the historical significance and physicality of ceramic form.
        </p>
      </div>
    </section>
  </div>
</template>